# Generated by Django 4.1.1 on 2022-09-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('desc', models.TextField(blank=True, default=None, null=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('color', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('size', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('quantity', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
