# Generated by Django 4.1.1 on 2022-09-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_kartelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartelement',
            name='total_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
