# Generated by Django 4.1.1 on 2022-09-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_kartelement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kartelement',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='kartelement',
            name='size',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
