# Generated by Django 4.1.1 on 2022-09-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_kartelement_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kartelement',
            old_name='product_name',
            new_name='product_title',
        ),
    ]
