# Generated by Django 4.1.1 on 2022-09-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_product_name_kartelement_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='kartelement',
            name='product_image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
