# Generated by Django 4.1.1 on 2022-09-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_kartelement_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kartelement',
            name='product_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
