# Generated by Django 4.1.1 on 2022-09-26 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_kartelement_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('Phone_Number', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('address', models.TextField(blank=True, default=None, max_length=True, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('state', models.CharField(blank=True, max_length=11, null=True)),
                ('pincode', models.CharField(blank=True, max_length=11, null=True)),
                ('total_ordered_price', models.IntegerField(blank=True, max_length=11, null=True)),
                ('payment_method', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('payment_id', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('message', models.TextField(blank=True, default=None, max_length=True, null=True)),
                ('tracking_no', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('created_at_time', models.CharField(blank=True, default='5:22:56 pm', max_length=11, null=True)),
                ('updated_at_time', models.CharField(blank=True, default='5:22:56 pm', max_length=11, null=True)),
                ('created_at_date', models.CharField(blank=True, default='23rd September 2022', max_length=11, null=True)),
                ('updated_at_date', models.CharField(blank=True, default='23rd September 2022', max_length=11, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('quantity', models.IntegerField(blank=True, default=None, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
