# Generated by Django 4.1.1 on 2022-09-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_price_ordereditem_price_of_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='total_price',
            new_name='total_ordered_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at_time',
            field=models.CharField(blank=True, default='10:19:27 pm', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at_time',
            field=models.CharField(blank=True, default='10:19:27 pm', max_length=225, null=True),
        ),
    ]
