# Generated by Django 4.1.1 on 2022-09-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_total_price_ordereditem_total_ordered_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Out For Shipping'), (3, 'Delivered')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(blank=True, choices=[(1, 'PENDING'), (2, 'FAILURE'), (3, 'SUCCESS')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_signature',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at_time',
            field=models.CharField(blank=True, default='10:33:45 am', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at_time',
            field=models.CharField(blank=True, default='10:33:45 am', max_length=225, null=True),
        ),
    ]
