# Generated by Django 4.1.1 on 2022-09-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_order_final_amount_with_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at_time',
            field=models.CharField(blank=True, default='10:02:18 pm', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_amount_with_gst',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at_time',
            field=models.CharField(blank=True, default='10:02:18 pm', max_length=225, null=True),
        ),
    ]
