# Generated by Django 4.1.1 on 2022-09-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_order_created_at_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at_date',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at_time',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at_date',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at_time',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
