# Generated by Django 4.1.1 on 2022-09-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_ordereditem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='user',
        ),
    ]
