# Generated by Django 4.1.1 on 2022-09-29 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0031_remove_ordereditem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='user',
            field=models.ForeignKey(default='pradeep', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
