# Generated by Django 4.1.1 on 2022-09-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_ordereditem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='title_of_product',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
