# Generated by Django 4.1.1 on 2022-09-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_ordereditem_title_of_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='final_amount_with_gst',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
